#!/bin/sh


REFERENCE_GENOME=Mouse_tRNA_rRNA_snRNAreference.fa


INDEX_NAME="${REFERENCE_GENOME%.*}"
mkdir -p bowtie2_index/$INDEX_NAME
echo ./bowtie2_index/$INDEX_NAME/$INDEX_NAME

bsub ./bowtie2_build.lsf $REFERENCE_GENOME ./bowtie2_index/$INDEX_NAME/$INDEX_NAME



#!/bin/bash
#BSUB -J bowtie2_build
#BSUB -P acc_pMorpheus
#BSUB -q express
#BSUB -n 4
#BSUB -R rusage[mem=8000]
#BSUB -W 00:30
#BSUB -o ./bowtie2_index/bowtie2_build.out
#BSUB -eo ./bowtie2_index/bowtie2_build.err
#BSUB -L /bin/bash

module load python

bowtie2 bowtie2-build --threads 10 -f "$1" "$2"

../tools/kallisto/build/src/kallisto index -k 11 -i $2.idx $1