#!/bin/bash
#BSUB -J samIndex
#BSUB -P acc_pMorpheus
#BSUB -q express
#BSUB -n 2
#BSUB -R "rusage[mem=3G]"           # Memory requirements
#BSUB -R "span[hosts=1]"              # All cores on the same node
#BSUB -W 10:00
#BSUB -o /sc/arion/work/penan08/log_files/samtool_indexOnly_%J.stdout
#BSUB -eo /sc/arion/work/penan08/log_files/samtool_indexOnly_%J.stderr
#BSUB -L /bin/bash

set -euo pipefail

#-- Load modules ----

module load samtools

#--working dir ---

working_dir="/sc/arion/projects/pMorpheus/noah/3_APOBEC3_analysis/STAR_output/apobec3_sep_reps/BAM_output/BAM_withRG_output/"



#Looping over the list, adding the RGID, RGLB, RGPL, RGPU, RGSM
for file in $working_dir/*rg.sorted.bam ; do

  echo "Indexing file: $file"
  samtools index $file
done

echo "Done"