#!/usr/bin/env bash
#BSUB -J __JOB_NAME__                   # will be replaced by samaple name e.g. cogent_0401_121520
#BSUB -P acc_pMorpheus
#BSUB -q express
#BSUB -n 18
#BSUB -R "rusage[mem=3000]"             # Memory requirements
#BSUB -R "span[hosts=1]"
#BSUB -W 08:00
#BSUB -o /sc/arion/work/penan08/log_files/__JOB_NAME__.out
#BSUB -eo /sc/arion/work/penan08/log_files/__JOB_NAME__.err

#set -euo pipefail

# load your conda environment
module load miniforge3
module load anaconda3/latestß
source activate /sc/arion/projects/pMorpheus/noah/Cogent_AP/CogentAP_tools

eval "$(conda shell.bash hook)"

# Run cogent demux
#KEEP DEBUG HIGH TO RETAIN CUTADAPT TRIMMING OUTPUT
/sc/arion/projects/pMorpheus/noah/Cogent_AP/cogent analyze \
    -g hg38 \
    -i "__INPUTDIR__" \
    -t SMARTSeq_FLA_UMI \
    --threads 18 \
    --debug high \
    -o "__OUTDIR__/"
