#!/bin/bash
#BSUB -J bowtie2_build
#BSUB -P acc_pMorpheus
#BSUB -q express
#BSUB -n 10
#BSUB -R "span[hosts=1]"             # All cores on the same node
#BSUB -R rusage[mem=8000]
#BSUB -W 08:00
#BSUB -o /sc/arion/work/penan08/log_files/bowtie2Build_%J.stdout
#BSUB -eo /sc/arion/work/penan08/log_files/bowtie2Build_%J.stderr
#BSUB -L /bin/bash

# Load required modules
module load bowtie2

# Variables
REFERENCE_GENOME="/sc/arion/work/penan08/5_huntingtonProject/pathoRepeatAnalysis/HTT_repeatRegion.fa"
#Get index_name
INDEX_NAME=$(basename "$REFERENCE_GENOME" .fa)    # strip .fa


# Create output directory
output_dir="/sc/arion/work/penan08/ref_seq/bowtie2_index/$INDEX_NAME"
mkdir -p $output_dir

# Output directory logging
echo "Bowtie2 index will be built at: $output_dir"

# Run bowtie2-build
bowtie2-build --threads 10 -f "$REFERENCE_GENOME" "$output_dir/$INDEX_NAME"