#!/bin/bash

# LSF job directives
#BSUB -J bowtie2_batch                # Job name
#BSUB -P acc_pMorpheus                # Project name
#BSUB -q express                      # Queue name
#BSUB -n 10                           # Number of cores
#BSUB -R "rusage[mem=3000]"           # Memory requirements
#BSUB -R "span[hosts=1]"              # All cores on the same node
#BSUB -W 06:00                        # Walltime (HH:MM)
#BSUB -oo ./logs/%J.stdout # Standard output file
#BSUB -eo ./logs/%J.stderr # Standard error file
#BSUB -L /bin/bash                    # Shell to use


