#!/bin/bash

# LSF job directives
#BSUB -J starAlign             # Job name
#BSUB -P acc_pMorpheus                # Project name
#BSUB -q express                      # Queue name
#BSUB -n 10                           # Number of cores
#BSUB -R "rusage[mem=3000]"           # Memory requirements
#BSUB -R "span[hosts=1]"              # All cores on the same node
#BSUB -W 02:00                        # Walltime (HH:MM)
#BSUB -o ./7_star/star.stdout # Standard output file
#BSUB -eo ./7_star/star.stderr # Standard error file
#BSUB -L /bin/bash                    # Shell to use

# --- Setup ---
# Define variables
reference="/sc/arion/projects/pMorpheus/noah/1_SusannaRNAseq_2024_11_05/ref_seq/star_index/APOBEC3A_H/"
output_dir="/sc/arion/projects/pMorpheus/noah/1_SusannaRNAseq_2024_11_05/7_star"
input_dir="/sc/arion/projects/pMorpheus/noah/1_SusannaRNAseq_2024_11_05/0_trimmed/"
readFileManifest="/sc/arion/projects/pMorpheus/noah/1_SusannaRNAseq_2024_11_05/ref_seq/star_index/manifest.tsv" #EDIT 
index_file="APOBEC3A-H"


# Create output directories
mkdir -p "$output_dir"
mkdir -p "$output_dir/$index_file"

# Load necessary modules
module load star

# Run star
STAR --runThreadN 8 --genomeDir "$reference" \
    --readFilesIn "$input_dir" \
    --readFilesManifest "$readFileManifest" \
    --readFilesCommand gunzip -c \
    --outFilterMultimapNmax 100 \
    --winAnchorMultimapNmx 150 \
    --seedPerWindowNmax 10 #Added because using small genome 

echo "All samples have been processed successfully!"